Repository SAP-samples/btp-terraform-samples, pull requests merged in 2023-10, with the labels that each got.

#55 chore: update Terraform provider version to 0.5.0-beta1
  in-development/discovery_center/mission_4024/modules/services_apps/sap_build_apps/standard/sap_build_apps.tf
  in-development/discovery_center/mission_4024/provider.tf
  in-development/uc_btp_resillient_apps/provider.tf
  in-development/uc_multi_provider_setup/provider.tf
  in-development/uc_subaccount_setup/provider.tf
  in-development/uc_trial_cf_deployment/provider.tf
  released/modules/environment/cloudfoundry/envinstance_cf/envinstance_cf.tf
  released/modules/services_apps/sap_build_apps/standard/sap_build_apps.tf
  released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup.tf
  released/usecases/dev_test_prod_setup/provider.tf
  released/usecases/multi_account_setup/modules/subaccount_setup/subaccount_setup.tf
  released/usecases/multi_account_setup/provider.tf
  released/usecases/services_apps/sap_build_apps/provider.tf
Labels: dependencies

#56 update on variables
  released/usecases/services_apps/sap_build_apps/main.tf
  released/usecases/services_apps/sap_build_apps/variables.tf
Labels: bug

#52 DC Mission: Events to Business Actions Use Case
  released/discovery_center/mission_4172/README.md
  released/discovery_center/mission_4172/main.tf
  released/discovery_center/mission_4172/provider.tf
  released/discovery_center/mission_4172/samples.tfvars
  released/discovery_center/mission_4172/variables.tf
Labels: enhancement

#58 fix: broken link
  in-development/uc_subaccount_setup/README.md
Labels: bug, broken link
